<?php

/**
 * @file
 * Install, update and uninstall functions for uc_custom_product_search module.
 */

/**
 * Implements hook_uninstall().
 */
function uc_custom_product_search_uninstall() {
  $query = db_select('variable', 'v')
    ->fields('v', array('name'))
    ->condition('name', db_like('uc_custom_product_search') . '%', 'LIKE')
    ->execute();
  while ($variable = $query->fetchAssoc()) {
    variable_del($variable['name']);
  }
}
